[tools]
deno = "latest"
hk = "latest"
pkl = "latest"

[tasks.build]
description = "Build the CLI binary"
run = [
    "deno install",
    "deno compile -A --target $ARCH -o dist/konaste-$ARCH src/main.ts",
]
env.ARCH = "x86_64-unknown-linux-gnu"
